version: '3.7'

services:

  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: server
    image: jguzmanjs/meanstack_backend
    ports:
      - '3000:3000'
    links:
      - mongo-db

  client:
    build: client
    image: jguzmanjs/meanstack_frontend
    ports:
      - '80:80'
